version: "3.9"
services:

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
