spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true

